## NumPy

In der vorherigen Lektion haben wir uns mit Listen beschäftigt. Diese sind sehr flexibel, aber auch sehr langsam. Mit kleinen Listen werden wir das nicht merken, aber wenn wir mit großen Datenmengen arbeiten, dann können lange Laufzeiten zum Problem werden. 

NumPy (Numerical Python) ist ein Paket, das viele Funktionen enthält, die für die Arbeit mit großen Datenmengen geeignet sind.

In [1]:
import numpy as np
from time import process_time

In [2]:
# Wir können eine Liste in ein NumPy-Array umwandeln
python_list = range(int(1e6))
numpy_array = np.array(python_list)

In [3]:
start_zeit = process_time()

a_list_plus_2 = [i + 2 for i in python_list]

end_zeit = process_time()
round(end_zeit - start_zeit, 5)

0.02992

In [4]:
start_zeit_1 = process_time()

a_array_plus_2 = numpy_array + 2

end_zeit_1 = process_time()
round(end_zeit_1 - start_zeit_1, 5)

0.0016

In [5]:
x = np.array([2, 7, 5, 2])
y = np.ones(4)
y

array([1., 1., 1., 1.])

NumPy-Arrays sind sehr ähnlich zu Listen, aber sie haben einige zusätzliche Eigenschaften. Zum Beispiel können wir mit NumPy-Arrays rechnen. Wenn wir zwei NumPy-Arrays addieren, dann werden die Elemente an der gleichen Stelle addiert. Diese Syntax ist sehr intuitiv und einfach zu lesen.


In [6]:
z1 = x + 1 
z2 = x + y
z1

array([3, 8, 6, 3])

In [7]:
z2

array([3., 8., 6., 3.])

Dasselbe funktioniert mit Python-Listen nicht. Wenn wir zwei Listen addieren, dann werden die Elemente an der gleichen Stelle nicht addiert, sondern die Listen werden aneinander gehängt.

In [8]:
x_list = [2, 7, 5, 2]
y_list = [1, 1, 1, 1]
x_plus_y_list = x_list + y_list
x_plus_y_list

[2, 7, 5, 2, 1, 1, 1, 1]

In [9]:
# x_list + 1

NumPy-Arrays haben auch einige Methoden, die wir mit Listen nicht haben. Zum Beispiel können wir die Summe aller Elemente eines Arrays berechnen.

In [10]:
# Summe der Elemente
x.sum()

16

In [11]:
# Durchschnitt der Elemente (Arithmetischer Mittelwert)

x.mean()

4.0

In [12]:
# Standardabweichung
x.std()

2.1213203435596424

In [13]:
# Minimum
x.min()

2

In [14]:
# Maximum
x.max()

7

In [15]:
# Der Index des Minimums
x.argmin()

0

In [16]:
# Der Index des Maximums
x.argmax()

1

### Slicing

Wir können auch auf die Elemente eines Arrays zugreifen, indem wir einen Index angeben. Der Index beginnt bei 0.

In [17]:
z = np.array(["a", "b", "c", "d", "e"])

In [18]:
# Das erste Element
z[0]

'a'

In [19]:
# Alle Elemente bis zur Indexposition 2 (exklusive)
# Achten Sie darauf, dass der Index 0-basiert ist und daher das dritte Element ist eine Indexposition 2 hat
z[:2]

array(['a', 'b'], dtype='<U1')

In [20]:
z[-3]

'c'

In [21]:
z[-3:]

array(['c', 'd', 'e'], dtype='<U1')

In [22]:
z[1:3]

array(['b', 'c'], dtype='<U1')

In [23]:
z[::2]

array(['a', 'c', 'e'], dtype='<U1')

In [24]:
z[::-1]

array(['e', 'd', 'c', 'b', 'a'], dtype='<U1')

### Arrays und Listen Zuweisung

Eine zugängige Erläuterung, wie Werte im Speicher des Rechners gespeichert werden, finden Sie in [hier](https://mvschamanth.medium.com/inside-python-are-variables-memory-references-a7522808be93).

In [25]:
z[1] = "x"
z

array(['a', 'x', 'c', 'd', 'e'], dtype='<U1')

In [26]:
z1 = z

In [27]:
z[0] = "X"

In [28]:
z1

array(['X', 'x', 'c', 'd', 'e'], dtype='<U1')

In [29]:
z1 == z

array([ True,  True,  True,  True,  True])

In [30]:
print(id(z1))
print(id(z))

131197187457264
131197187457264


In [31]:
l1 = [1, 2, 3]
l2 = l1

print(id(l1))
print(id(l2))

131198305796480
131198305796480


In [32]:
s1 = "Some string"
s2 = s1

print(id(s1))
print(id(s2))

# s1[0] = "X"

131198237230768
131198237230768
