## NumPy

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/febse/opt2025-de/blob/main/01-Python/02-Numpy.ipynb)

In der vorherigen Lektion haben wir uns mit Listen beschäftigt. Diese sind sehr flexibel, aber auch sehr langsam. Mit kleinen Listen werden wir das nicht merken, aber wenn wir mit großen Datenmengen arbeiten, dann können lange Laufzeiten zum Problem werden. 

NumPy (Numerical Python) ist ein Paket, das viele Funktionen enthält, die für die Arbeit mit großen Datenmengen geeignet sind.

In [2]:
import numpy as np

x = np.array([2, 7, 5, 2])
print(x)

y = np.ones(4)
print(y)

[2 7 5 2]
[1. 1. 1. 1.]


NumPy-Arrays sind sehr ähnlich zu Listen, aber sie haben einige zusätzliche Eigenschaften. Zum Beispiel können wir mit NumPy-Arrays rechnen. Wenn wir zwei NumPy-Arrays addieren, dann werden die Elemente an der gleichen Stelle addiert. Diese Syntax ist sehr intuitiv und einfach zu lesen.


In [3]:
z1 = x + 1 
z2 = x + y
z1

array([3, 8, 6, 3])

In [4]:
z2

array([3., 8., 6., 3.])

Dasselbe funktioniert mit Python-Listen nicht. Wenn wir zwei Listen addieren, dann werden die Elemente an der gleichen Stelle nicht addiert, sondern die Listen werden aneinander gehängt.

In [5]:
x_list = [2, 7, 5, 2]
y_list = [1, 1, 1, 1]
x_plus_y_list = x_list + y_list
x_plus_y_list

[2, 7, 5, 2, 1, 1, 1, 1]

In [6]:
# x_list + 1

NumPy-Arrays haben auch einige Methoden, die wir mit Listen nicht haben. Zum Beispiel können wir die Summe aller Elemente eines Arrays berechnen.

In [7]:
# Summe der Elemente
print(x.sum())

16


In [11]:
# Durchschnitt der Elemente (Arithmetischer Mittelwert)

x.mean()

np.float64(4.0)

In [12]:
# Standardabweichung
x.std()

np.float64(2.1213203435596424)

In [13]:
# Minimum
x.min()

np.int64(2)

In [14]:
# Maximum
x.max()

np.int64(7)

## Aufgabe 1

Estellen Sie ein NumPy-Array mit den Elementen 3, 1, 11, 3, 5. Geben Sie das Array aus. 
- Testen Sie, ob die Elemente des Arrays genau gleich 3 sind, speichern Sie das Ergebnis in einer Variablen. Geben Sie das Ergebnis aus.
- Berechnen Sie die Differenz zwischen dem Maximum und dem Minimum des Arrays. Geben Sie das Ergebnis aus.
- Berechnen Sie den Mittelwert des Arrays. Geben Sie das Ergebnis aus.


array([ True, False, False,  True])

### Slicing

Wir können auch auf die Elemente eines Arrays zugreifen, indem wir einen Index angeben. Der Index beginnt bei 0.

In [6]:
z = np.array(["a", "b", "c", "d", "e"])

In [8]:
# Das erste Element
print(z[0])

a


In [9]:
# Alle Elemente bis zur Indexposition 2 (exklusive)
# Achten Sie darauf, dass der Index 0-basiert ist und daher das dritte Element ist eine Indexposition 2 hat
z[:2]

array(['a', 'b'], dtype='<U1')

In [16]:
print(z[-3])

c


In [12]:
print(z[-3:])

['c' 'd' 'e']


In [13]:
z[1:3]

array(['b', 'c'], dtype='<U1')

## Aufgabe 2

- Erstellen Sie ein NumPy-Array mit den Elementen 2.2, 3.1, 8.2, 9. Geben Sie das Array aus.
- Ersetzen Sie die ersten beiden Elemente des Arrays durch die Werte 1.1 und 2.2. Geben Sie das Array aus.
- Testen Die, ob das letzte Element des Arrays größer als 10 ist. Speichern Sie das Ergebnis in einer Variablen. Geben Sie das Ergebnis aus.
