# Cocktails und duale Preise (Übung)

Open in Colab: [![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/febse/opt2025-de/blob/main/Duality-Ex.ipynb)

- [Cocktails (shared)](https://febunisofia-my.sharepoint.com/:x:/g/personal/amarov_feb_uni-sofia_bg/ESP-SwOFNNhGpNlhQtnI1xsBrR8nw-eklsYqMyCA-eJiAw?e=Tfqjsq&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0)
- [Cocktails (download)](https://github.com/febse/data/raw/refs/heads/main/opt/Cocktails_2d.xlsx)

In [ ]:
%pip install gurobipy plotly sympy

import numpy as np
import plotly.graph_objects as go
import pandas as pd
import gurobipy as gp
from gurobipy import GRB

Note: you may need to restart the kernel to use updated packages.


## Barmanagement

Stellen wir uns vor, dass wir eine kleine Bar managen. Wir sind so spezialisiert, dass wir nur Bloody Mary in zwei Varianten anbieten:

- _Bloody Mary Light (BML)_, der aus 20 ml Vodka und 80 ml Tomatensaft besteht
- _Bloody Mary Stark (BMS)_, der aus 40 ml Vodka und 60 ml Tomatensaft besteht

In einer Stunde haben 2000 ml Vodka und 4000 ml Tomatensaft zur Verfügung. Wie viele von beiden Cocktails sollten wir zubereiten, um den Gewinn zu maximieren? Ein Glass Bloody Mary Light (100 ml) bring uns 3 Euro Gewinn ein, ein Glass (100 ml) Bloody Mary Stark bringt uns 4 Euro Gewinn ein.

- Schreiben Sie das Modell zuerst auf Papier auf
- Lösen Sie das Modell mit Excel Solver
- Lösen Sie das Modell mit Gurobi in Python (einmal mit `.addVar` und einmal mit `.addMVar`)
- Formulieren Sie die duale Optimierungsaufgabe und lösen Sie diese mit Excel Solver und Gurobi (auch mit `.addVar` und `.addMVar`)

In [4]:
ressourcen = np.array([2000, 4000]) # ml Vodka, ml Tomatensaft

print("Ressourcen:", ressourcen)

gewinn_pro_coktail = np.array([3, 4])

print("Gewinn pro Cocktail:", gewinn_pro_coktail)

rezept_BML = np.array([20, 80]) # ml Vodka, ml Tomatensaft
rezept_BMS = np.array([40, 60]) # ml Vodka, ml Tomatensaft

bar_rezepte = np.array([rezept_BML, rezept_BMS])
bar_rezepte

Ressourcen: [2000 4000]
Gewinn pro Cocktail: [3 4]


array([[20, 80],
       [40, 60]])

In [7]:
# Berechnen Sie den Gewinn bei der Produktion von 10 BML und 10 BMS
gewinn_pro_coktail @ np.array([10, 10]) # Gewinn = Gewinn pro Cocktail * Anzahl Cocktails

np.int64(70)

In [6]:
verbrauchs_koeffizienten = bar_rezepte.T
print("Verbrauchskoeffizienten:\n", verbrauchs_koeffizienten)

verbrauch_vodka = verbrauchs_koeffizienten[0,:]
print("Verbrauch von Vodka:", verbrauch_vodka)

verbrauch_tomatensaft = verbrauchs_koeffizienten[1,:]
print("Verbrauch von Tomatensaft:", verbrauch_tomatensaft)


Verbrauchskoeffizienten:
 [[20 40]
 [80 60]]
Verbrauch von Vodka: [20 40]
Verbrauch von Tomatensaft: [80 60]


Berechnen Sie den Verbrauch von Vodka und Tomatensaft für die Produktion von 

- 2 Cocktails BML und 3 Cocktails BMS
- 3 Cocktails BML und 2 Cocktails BMS
- 4 Cocktails BML und 1 Cocktails BMS
- 1 Cocktails BML und 4 Cocktails BMS

Benutzen Sie dazu Formeln in Excel und `numpy` in Python

In [ ]:
# Verbrauch von Vodka bei der Produktion von 2 Bloody Mary Light und 3 Bloody Mary Stark
print("Verbrauch von Vodka: Produktion von 2 BML und 3 BMS:", verbrauch_vodka @ np.array([2, 3]))

# Verbrauch von Tomatensaft bei der Produktion von 2 Bloody Mary Light und 3 Bloody Mary Stark
print("Verbrauch von Tomatensaft: Produktion von 2 BML und 3 BMS:", verbrauch_tomatensaft @ np.array([2, 3]))

# Verbrauch Vodka: 3 BML und 2 BMS

# Verbrauch Tomatensaft: 3 BML und 2 BMS

# Verbrauch Vodka: 4 BML und 1 BMS

# Verbrauch Tomatensaft: 4 BML und 1 BMS

# Verbrauch Vodka: 1 BML und 4 BMS


Verbrauch von Vodka: Produktion von 2 BML und 3 BMS: 160
Verbrauch von Tomatensaft: Produktion von 2 BML und 3 BMS: 340


In [ ]:
# Verbrauch von Vodka und Tomatensaft: 2 BML und 3 BMS
print("Verbrauch von Vodka und Tomatensaft: 2 BML und 3 BMS:", verbrauchs_koeffizienten @ np.array([2, 3]))

# Verbrauch von Vodka und Tomatensaft: 3 BML und 2 BMS


# Verbrauch von Vodka und Tomatensaft: 4 BML und 1 BMS



Verbrauch von Vodka und Tomatensaft: 2 BML und 3 BMS: [160 340]


In [ ]:
# Modell erstellen

m = gp.Model("Cocktail")
m.Params.LogToConsole = 0 # keine Ausgabe in der Konsole

# Variablen definieren

x1 = m.addVar(name="Light") # Anzahl von Bloody Mary Light Cocktails
x2 = m.addVar(name="Stark") # Anzahl von Bloody Mary Stark Cocktails

# Zielfunktion definieren

m.setObjective(3 * x1 + 4 * x2, GRB.MAXIMIZE)

# Nebenbedingungen definieren


# m.optimize()

m.write("cocktail.lp") # Speichern des Modells in einer Datei

with open("cocktail.lp", "r") as f:
    print(f.read())

# Ergebnisse ausgeben

# print("Optimaler Cocktailmix:")

# print(f"Bloody Mary Light: {x1.X:.2f} Stück")
# print(f"Bloody Mary Stark: {x2.X:.2f} Stück")

# # Die Nebenbedingungen ausgeben als pandas DataFrame

# # Die Nebenbedingungen ausgeben als pandas DataFrame
# constr_df = pd.DataFrame([
#     (c.ConstrName, c.Pi, c.Slack, c.RHS) for c in m.getConstrs()],
#     columns=["Name", "Schattenpreis", "Slack", "RHS"]
# )
# constr_df

Restricted license - for non-production use only - expires 2026-11-23
Set parameter LogToConsole to value 0
\ Model Cocktail
\ LP format - for model browsing. Use MPS format to capture full model detail.
Maximize
  3 Light + 4 Stark
Subject To
 Vodka: 20 Light + 40 Stark <= 2000
 Tomatensaft: 80 Light + 60 Stark <= 4000
Bounds
End

Optimaler Cocktailmix:
Bloody Mary Light: 20.00 Stück
Bloody Mary Stark: 40.00 Stück


Name  Schattenpreis  Slack     RHS
0        Vodka           0.07    0.0  2000.0
1  Tomatensaft           0.02    0.0  4000.0

In [ ]:
# Dasselbe in kürzerer Form

m1 = gp.Model("Cocktail 2")
m1.Params.LogToConsole = 0 # keine Ausgabe in der Konsole

x = m1.addMVar(2, name="Cocktails")

# Zielfunktion definieren

# Nebenbedingungen definieren


# m1.optimize()

# # Ergebnisse ausgeben
# print("Optimaler Cocktailmix:")
# print(f"Bloody Mary Light: {x.X[0]:.2f} Stück")
# print(f"Bloody Mary Stark: {x.X[1]:.2f} Stück")

# m1.write("cocktail-2.lp")

# with open("cocktail-2.lp") as f:
#     print(f.read())

# # Die Nebenbedingungen ausgeben als pandas DataFrame
# constr_df = pd.DataFrame([
#     (c.ConstrName, c.Pi, c.Slack, c.RHS) for c in m1.getConstrs()],
#     columns=["Name", "Schattenpreis", "Slack", "RHS"]
# )
# constr_df

Set parameter LogToConsole to value 0
Optimaler Cocktailmix:
Bloody Mary Light: 20.00 Stück
Bloody Mary Stark: 40.00 Stück
\ Model Cocktail 2
\ LP format - for model browsing. Use MPS format to capture full model detail.
Maximize
  3 Cocktail[0] + 4 Cocktail[1]
Subject To
 Rezept[0]: 20 Cocktail[0] + 40 Cocktail[1] <= 2000
 Rezept[1]: 80 Cocktail[0] + 60 Cocktail[1] <= 4000
Bounds
End



Name  Slack     RHS  Schattenpreis Sense
0  Rezept[0]    0.0  2000.0           0.07     <
1  Rezept[1]    0.0  4000.0           0.02     <

## Das duale Problem

Schauen wir uns eine einfache Optimierungsaufgabe an:

$$
\begin{align*}
\text{max} & \quad 2x_1 + 3x_2 \\
\text{s.t.} & \quad x_1 + x_2 \leq 8 \\
& \quad x_1 + 2 x_2 \leq 12 \\
& x_1, x_2 \geq 0
\end{align*}
$$

Ihre Lösung ist $[x_1, x_2] = [4, 4]$, also erreichen wir den grösstmöglichen Gewinn von $2 \cdot 4 + 3 \cdot 4 = 20$ Euro. Können wir aber **beweisen**, dass es keinen grösseren Gewinn gibt?
 

Die duale Aufgabe zur Barmanagement-Optimierung ist:

$$
\begin{align*}
\text{min} & \quad 2000 y_1 + 4000 y_2 \\
\text{s.t.} & \quad 20 y_1 + 80 y_2 \geq 3 \\
& \quad 40 y_1 + 60 y_2 \geq 4 \\
& \quad y_1, y_2 \geq 0 \\
\end{align*}
$$



In [9]:
# Das duale Problem (1)

md = gp.Model("Cocktail dual")
md.Params.LogToConsole = 0 # keine Ausgabe in der Konsole

y1 = md.addVar(name="Wert von Vodka") # Schattenpreis Vodka
y2 = md.addVar(name="Wert von Tomatensaft") # Schattenpreis Tomatensaft

# Einschränkungen definieren


# Kontrolle: das LP ausgeben
md.write("cocktail-dual.lp") # Speichern des Modells in einer Datei

with open("cocktail-dual.lp", "r") as f:
    print(f.read())

# md.optimize()

# # Ergebnisse ausgeben
# print("Optimale Werte der Ressourcen:")

# print(f"Wert von Vodka: {y1.X:.2f} Euro /ml")
# print(f"Wert von Tomatensaft: {y2.X:.2f} Euro/ml")
# print(f"Gewinn: {md.ObjVal:.2f} Euro")

# # Die Nebenbedingungen ausgeben als pandas DataFrame
# constr_df = pd.DataFrame([
#     (c.ConstrName, c.Slack, c.RHS, c.Pi, c.Sense) for c in md.getConstrs()], 
#     columns=["Name", "Slack", "RHS", "Schattenpreis", "Sense"
# ])

# constr_df


Set parameter LogToConsole to value 0
\ Model Cocktail dual
\ LP format - for model browsing. Use MPS format to capture full model detail.
Minimize
  0 Wert_von_Vodka + 0 Wert_von_Tomatensaft
Subject To
Bounds
End



In [ ]:
# Das Duale Problem (2)

m2 = gp.Model("Cocktail Dual 2")

m2.Params.LogToConsole = 0 # keine Ausgabe in der Konsole

# Variablen definieren (mit addMVar)

# Zielfunktion definieren


# Nebenbedingungen definieren (mit addConstr)

# m2.optimize()

m2.write("cocktail-dual-2.lp") # Speichern des Modells in einer Datei

with open("cocktail-dual-2.lp", "r") as f:
    print(f.read())

# # Ergebnisse ausgeben
# print("Schattenpreise:")

# print(f"Wert von Vodka: {y.X[0]:.2f} Euro/ml")
# print(f"Wert von Tomatensaft: {y.X[1]:.2f} Euro/ml")
# print(f"Gewinn: {m2.ObjVal:.2f} Euro")
# # Die Nebenbedingungen ausgeben als pandas DataFrame

# constr_df = pd.DataFrame([
#     (c.ConstrName, c.Slack, c.RHS, c.Pi, c.Sense) for c in m2.getConstrs()],
#     columns=["Name", "Slack", "RHS", "Schattenpreis", "Sense"
# ])

# constr_df


Set parameter LogToConsole to value 0
\ Model Cocktail Dual 2
\ LP format - for model browsing. Use MPS format to capture full model detail.
Minimize
  2000 Werte[0] + 4000 Werte[1]
Subject To
 Cocktail[0]: 20 Werte[0] + 80 Werte[1] >= 3
 Cocktail[1]: 40 Werte[0] + 60 Werte[1] >= 4
Bounds
End

Schattenpreise:
Wert von Vodka: 0.07 Euro/ml
Wert von Tomatensaft: 0.02 Euro/ml
Gewinn: 220.00 Euro


Name  Slack  RHS  Schattenpreis Sense
0  Cocktail[0]    0.0  3.0           20.0     >
1  Cocktail[1]    0.0  4.0           40.0     >

In [ ]:
# Wie viel von den Resourcen verbrauchen wir, falls wir 2 BML und 2 BLS machen?

bar_rezepte @ np.array([1, 1])

array([100, 100])

# Cocktails mit drei Zutaten


In [ ]:
# Ingredients 100 ml vodka, 100 ml rum, 100 ml tomato juice
zutaten_3 = np.array([1, 1, 1])

# Rezepte (in ml)

bloody_mary_rezept = np.array([20, 0, 80])
rum_pure_rezept = np.array([0, 50, 0])
crazy_rezept = np.array([40, 40, 20])

alle_rezepte = np.stack([
    bloody_mary_rezept,
    rum_pure_rezept,
    crazy_rezept
])

rezept_namen = [
    "Bloody Mary Rezept",
    "Rum Pure Rezept",
    "Crazy Cocktail Rezept"
]

cocktail_colors = [
    "firebrick",
    "steelblue",
    "orange"
]

# Create a 3D scatter plot with plotly showing the rows of all_cocktails as vectors 

fig = go.Figure()

# Add each cocktail as a vector
for i, cocktail in enumerate(alle_rezepte):
    fig.add_trace(go.Scatter3d(
        x=[0, cocktail[0]],  # Start at origin (0, 0, 0)
        y=[0, cocktail[1]],
        z=[0, cocktail[2]],
        mode='lines+markers',
        name=rezept_namen[i],
        line=dict(color=cocktail_colors[i], width=5),
        marker=dict(size=5)
    ))

# Set plot layout
fig.update_layout(
    title="3D Diagram der Cocktails",
    scene=dict(
        xaxis=dict(
            title="Vodka",
            range=[0, 1]
        ),
        yaxis=dict(
            title="Rum",
            range=[0, 1]
        ),
        zaxis=dict(
            title="Tomatensaft",
            range=[0, 1]
        )
    )
)

# Show the plot
fig.show()

## Modifikation von Rezepten


In [ ]:

# Nimm die Zutaten, erhöhe die erste Zutat (Vodka) um 20 Prozent, ignoriere alle anderen Zutaten
nimm_den_vodka_verdoppele_ihn_und_ignoriere_den_rest = np.array([2, 0, 0])

# Nimm die zweite Zutat (Rum), verändere die Menge nicht, ignoriere alle anderen Zutaten
nimm_nur_den_rum_so_wie_er_ist = np.array([0, 1, 0])

# Nimm die dritte Zutat (Tomato Juice), verändere die Menge nicht, ignoriere alle anderen Zutaten
nimm_den_tomatensaft_so_wie_er_ist = np.array([0, 0, 1])

In [ ]:
verdoppele_den_vodka_im_rezept = np.stack([
    nimm_den_vodka_verdoppele_ihn_und_ignoriere_den_rest,
    nimm_nur_den_rum_so_wie_er_ist,
    nimm_den_tomatensaft_so_wie_er_ist
])

verdoppele_den_vodka_im_rezept

array([[2, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
modifizierte_rezepte = verdoppele_den_vodka_im_rezept @ alle_rezepte.T
print(alle_rezepte)
modifizierte_rezepte.T

[[0.3 0.  0.6]
 [0.  0.4 0. ]
 [0.4 0.4 0.3]]


array([[0.6, 0. , 0.6],
       [0. , 0.4, 0. ],
       [0.8, 0.4, 0.3]])

In [ ]:
# Create a 3D scatter plot with plotly showing the rows of all_cocktails as vectors 

# Add each cocktail as a vector
for i, cocktail in enumerate(modifizierte_rezepte.T):
    fig.add_trace(go.Scatter3d(
        x=[0, cocktail[0]],  # Start at origin (0, 0, 0)
        y=[0, cocktail[1]],
        z=[0, cocktail[2]],
        mode='lines+markers',
        name=f"{rezept_namen[i]} modifiziert",
        line=dict(color=cocktail_colors[i], width=5, dash='dash'),
        marker=dict(size=5)
    ))

fig.update_layout(
    title = "3D Diagram der Cocktails: die originalen Rezepte und die modifizierten Rezepte",
)
# Show the plot
fig.show()

In [ ]:
bloody_mary_mit_doppelt_vodka_rezept = verdoppele_den_vodka_im_rezept @ bloody_mary_rezept
bloody_mary_mit_doppelt_vodka_rezept

array([0.6, 0. , 0.6])

In [ ]:
crazy_mit_doppelt_vodka_rezept = crazy_rezept @ verdoppele_den_vodka_im_rezept
crazy_mit_doppelt_vodka_rezept

array([0.8, 0.4, 0.3])

In [ ]:
switch_vodka_and_tomato = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0]
])
switch_vodka_and_tomato

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])