In [13]:
import numpy as np
import plotly.graph_objects as go

In [18]:
A = np.array([[1, 1], [0, 1]])

ev, evecs = np.linalg.eig(A)
evecs

array([[ 1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  2.22044605e-16]])

In [19]:
ev

array([1., 1.])

In [20]:
evecs.T @ evecs

array([[ 1., -1.],
       [-1.,  1.]])


## Der Nullraum

Wir haben gesehen, dass die Transformation $C$ alle Rezepte auf eine Gerade abbildet. Einige Rezepte (in diesem Beispiel sind das keine realistischen Rezepte) bildet sie allerdings auf das leere Glass (den Nullpunkt).

Z.B (-1, 1) und alle Vielfachen davon:

$$
\begin{pmatrix}
1 & 1 \\
2 & 2 \\
\end{pmatrix}
\begin{pmatrix}
-1 \\
1 \\
\end{pmatrix} =
\begin{pmatrix}
-1 + 1 \\
-2 + 2 \\
\end{pmatrix} =
\begin{pmatrix}
0 \\
0 \\
\end{pmatrix}
$$

Wir sagen, dass alle Rezepte, die auf den Nullpunkt abgebildet werden, im Nullraum der Transformation liegen.

In [16]:
C @ np.array([-1, 1])

NameError: name 'C' is not defined

## Die Rotationsrichtungen

Wir haben gesehen, dass eine Transformation ein Rezept drehen und oder skalieren kann.

Schauen wir uns die folgende Transformation an:

$$
D = \begin{pmatrix}
1 & 2 \\
3 & 1 \\
\end{pmatrix}
$$


Wenden wir diese Transformation auf BM Light an

$$
\begin{pmatrix}
1 & 2 \\
3 & 1 \\
\end{pmatrix}
\begin{pmatrix}
20 \\
80 \\
\end{pmatrix} =
\begin{pmatrix}
20 + 2 \cdot 80 \\
3 \cdot 20 + 80 \\
\end{pmatrix} =
\begin{pmatrix}
180 \\
140 \\
\end{pmatrix}
$$

Wir sehen gleich, dass das neue Rezept unterschiedliche Anteile von Vodka und Tomatensaft hat (Drehung) und gleichzeitig eine andere Menge produziert (Skalierung).


In [ ]:
D = np.array([
    [1, 2],
    [3, 1]
])

D @ bm_light

array([180, 140])


Es ist nicht offensichtlich, aber zu jeder Transformation gibt es spezielle Rezepte, die von der Transformation **nicht** gedreht werden und wirken lediglich, als ob wir sie mit einer Zahl multipliziert hätten (Skalierung).

Wie finden wir diese speziellen Rezepte? Falls die Transformation nur die Mengen skaliert, dann ist das Rezept ein Vielfaches der Zeilen der Transformation:

$$
\begin{pmatrix}
1 & 2 \\
3 & 1 \\
\end{pmatrix}
\begin{pmatrix}
v_1 \\
v_2 \\
\end{pmatrix} =
\lambda \begin{pmatrix}
v_1 \\
v_2 \\
\end{pmatrix}
$$

Wenn wir die rechte Seite der Gleichung umstellen, erhalten wir:

$$
\begin{pmatrix}
1 & 2 \\
3 & 1 \\
\end{pmatrix}
\begin{pmatrix}
v_1 \\
v_2 \\
\end{pmatrix}
- \lambda \begin{pmatrix}
v_1 \\
v_2 \\
\end{pmatrix} = 0
$$

und wir können das Rezept in die Form bringen:

$$
\begin{pmatrix}
1 - \lambda & 2 \\
3 & 1 - \lambda \\
\end{pmatrix}
\begin{pmatrix}
v_1 \\
v_2 \\
\end{pmatrix} = 0
$$

Die neue Transformation soll also das Rezept auf den Nullpunkt abbilden. Wir haben schon gesehen, dass Transformationen, die auf den Nullpunkt abbilden, eine Determinante von 0 haben. Das ist auch die Bedingung, die wir hier haben:

$$
\text{det} \begin{pmatrix}
1 - \lambda & 2 \\
3 & 1 - \lambda \\
\end{pmatrix} = 0
$$

Das ist eine quadratische Gleichung in $\lambda$:

$$
(1 - \lambda)(1 - \lambda) - 2 \cdot 3 = 0
$$

Umformen ergibt:

$$
\lambda^2 - 2 \lambda - 5 = 0
$$

Die Lösungen sind:

$$
\lambda_1 = 1 - \sqrt{6} \quad \lambda_2 = 1 + \sqrt{6}
$$


In [ ]:
# Überprüfen wir, dass wir tatsächlich die Lösungen gefunden haben

lambda1 = 1 - np.sqrt(6)
lambda2 = 1 + np.sqrt(6)
print("Lambda 1:", lambda1)
print("Lambda 2:", lambda2)
print(lambda1 ** 2 - 2 * lambda1 - 5)
print(lambda2 ** 2 - 2 * lambda2 - 5)

Lambda 1: -1.4494897427831779
Lambda 2: 3.449489742783178
-8.881784197001252e-16
-1.7763568394002505e-15



Nehmen wir die zweite Lösung $\lambda_2$ und setzen sie in die Gleichung ein:


$$
\begin{pmatrix}
1 - (1 + \sqrt{6}) & 2 \\
3 & 1 - (1 + \sqrt{6}) \\
\end{pmatrix}
=
\begin{pmatrix}
-2.449 & 2 \\
3 & -2.449 \\
\end{pmatrix}
$$

$$
\begin{pmatrix}
-2.449 & 2 \\
3 & -2.449 \\
\end{pmatrix}
\begin{pmatrix}
v_1 \\
v_2 \\
\end{pmatrix} = 0
$$

Das ist ein lineares Gleichungssystem mit zwei Unbekannten. Wir können die Lösung finden, indem wir eine der Variablen setzen und die andere berechnen. _Eine Lösung_ erhalten wir, indem wir 
$v_1 = 1$ setzen und $v_2 = 1.224$ berechnen. Das ist ein Rezept, das von der Transformation $D$ nicht gedreht wird.

Ein Rezept, das von der Transformation $D$ nicht gedreht wird, ist also $(1, 1.224)$. Wir können das leicht überprüfen, indem wir die Transformation $D$ auf das Rezept anwenden:

In [ ]:
D @ np.array([1, 1.224])

array([3.448, 4.224])

In [ ]:
# Das selbe sollen wir erhalten, wenn wir die Lösung mit dem Rezept multiplizieren.

lambda2 * np.array([1, 1.224])

array([3.44948974, 4.22217545])

Auf dieselbe Art und Weise finden wir für die erste Lösung $\lambda_1$:

$$
\begin{pmatrix}
1 - (1 - \sqrt{6}) & 2 \\
3 & 1 - (1 - \sqrt{6}) \\
\end{pmatrix}
=
\begin{pmatrix}
2.449 & 2 \\
3 & 2.449 \\
\end{pmatrix}
$$

$$
\begin{pmatrix}
2.449 & 2 \\
3 & 2.449 \\
\end{pmatrix}
\begin{pmatrix}
v_1 \\
v_2 \\
\end{pmatrix} = 0
$$

Wie oben ist das ein lineares Gleichungssystem mit zwei Unbekannten. Wir setzen $v_1 = 1$ und berechnen $v_2 = -1.224$. Das ist ein Rezept, das von der Transformation $D$ nicht gedreht wird.

In [ ]:
D @ np.array([1, -1.224])

array([-1.448,  1.776])

In [ ]:
lambda1 * np.array([1, -1.224])

array([-1.44948974,  1.77417545])

In `numpy` können wir sowohl die Eigenwerte als auch die Eigenvektoren der Transformation $D$ mit `np.linalg.eig` berechnen. Die berechneten Eigenvektoren werden als Spaltenvektoren zurückgegeben.

In [ ]:
eigenv, eigenvecs = np.linalg.eig(D)

ev1, ev2 = eigenvecs
eigenv, (ev1, ev2)

(array([ 3.44948974, -1.44948974]),
 (array([ 0.63245553, -0.63245553]), array([0.77459667, 0.77459667])))

In [ ]:
np.array([1, 1.224]) / np.sqrt((np.array([1, 1.224])**2).sum())

array([0.63268638, 0.77440813])

In [ ]:
np.array([1, -1.224]) / np.sqrt((np.array([1, -1.224])**2).sum())

array([ 0.63268638, -0.77440813])

In [ ]:

ev1 = lambda1 * ev1 * 10
ev2 = lambda2 * ev2 * 10

# Plot the Eigenvectors

bm_light_tr_eigen = D @ bm_light

fig_eigen = go.Figure(data=[
                go.Scatter(x=[0, ev1[0]], y=[0, ev1[1]], mode='lines+markers', name='Eigenvektor 1', line=dict(color="black", width=2, dash="dash")),
                go.Scatter(x=[0, ev2[0]], y=[0, ev2[1]], mode='lines+markers', name='Eigenvektor 2', line=dict(color="black", width=2, dash="dash")),
                go.Scatter(x=[0, bm_light[0]], y=[0, bm_light[1]], mode='lines+markers', name='Light', line=dict(color="steelblue", width=2)),
                go.Scatter(x=[0, bm_light_tr_eigen[0]], y=[0, bm_light_tr_eigen[1]], mode='lines+markers', name='Light (transformiert)', line=dict(color="steelblue", width=2, dash="dash")),
                ])

fig_eigen.update_layout(
        title="Eigenvektoren der Transformation",
        xaxis_title="Vodka (ml)",
        yaxis_title="Tomatensaft (ml)",
        xaxis_range=[-40, 150],
        yaxis_range=[-40, 150],
        xaxis=dict(scaleanchor="y"),
        updatemenus=[dict(type="buttons",
                          buttons=[dict(args=[None, {"frame": {"duration": 20, "redraw": False},
                                                         "fromcurrent": True, "transition": {"duration": 10}}],
                                         label="Play",
                                         method="animate")])],
        legend=dict(
                orientation="h",  # Horizontal legend
                yanchor="bottom",  # Align the bottom of the legend
                y=1,             # Position above the plot (1.0 is the top of the plot)
                xanchor="center",  # Center the legend horizontally
                x=0.5              # Center position
        )
)

fig_eigen.show()

## Die Eigenzerlegung

Eine 

In [ ]:
eigenvecs

array([[ 0.63245553, -0.63245553],
       [ 0.77459667,  0.77459667]])

In [ ]:
(np.array([1, 0]) ** 2).sum()

np.int64(1)

In [ ]:
tmp = eigenvecs @ np.array([1, 0])
(tmp ** 2).sum()

np.float64(1.0)

In [ ]:
eigenvecs @ np.array([20, 0])

array([12.64911064, 15.49193338])

In [ ]:
(np.array([20, 0]) ** 2).sum()

np.int64(400)

In [ ]:
((eigenvecs @ np.array([20, 0])) ** 2).sum()

np.float64(400.00000000000006)

In [ ]:
np.linalg.norm(eigenvecs[:,1])

np.float64(1.0)

In [ ]:
eigenvecs

array([[ 0.63245553, -0.63245553],
       [ 0.77459667,  0.77459667]])

In [ ]:
eigenvecs.T

array([[ 0.63245553,  0.77459667],
       [-0.63245553,  0.77459667]])

In [ ]:
np.diag(eigenv)

array([[ 3.44948974,  0.        ],
       [ 0.        , -1.44948974]])

In [ ]:
(eigenvecs @ np.diag(eigenv)  @ np.linalg.inv(eigenvecs))

array([[1., 2.],
       [3., 1.]])

In [ ]:
# Plot the transformed basis recipes ((0, 20), (20, 0))

tomatensaft_pure_tr = eigenvecs @ tomatensaft_pure
vodka_pure_tr = eigenvecs @ vodka_pure

fig_eigen2 = go.Figure(data=[
                go.Scatter(x=[0, ev1[0]], y=[0, ev1[1]], mode='lines+markers', name='Eigenvektor 1', line=dict(color="black", width=2, dash="dash")),
                go.Scatter(x=[0, ev2[0]], y=[0, ev2[1]], mode='lines+markers', name='Eigenvektor 2', line=dict(color="black", width=2, dash="dash")),
                go.Scatter(x=[0, vodka_pure[0]], y=[0, vodka_pure[1]], mode='lines+markers', name='Vodka Pure', line=dict(color="steelblue", width=2)),
                go.Scatter(x=[0, tomatensaft_pure[0]], y=[0, tomatensaft_pure[1]], mode='lines+markers', name='Tomatensaft Pure', line=dict(color="firebrick", width=2)),
                go.Scatter(x=[0, vodka_pure_tr[0]], y=[0, vodka_pure_tr[1]], mode='lines+markers', name='Vodka Pure (transformation)', line=dict(color="steelblue", width=2, dash="dash")),
                go.Scatter(x=[0, tomatensaft_pure_tr[0]], y=[0, tomatensaft_pure_tr[1]], mode='lines+markers', name='Tomatensaft Pure (transformation)', line=dict(color="firebrick", width=2, dash="dash")),
                ])

fig_eigen2.update_layout(
        title="Eigenvektoren der Transformation",
        xaxis_title="Vodka (ml)",
        yaxis_title="Tomatensaft (ml)",
        xaxis_range=[-10, 30],
        yaxis_range=[-10, 30],
        xaxis=dict(scaleanchor="y"),
        legend=dict(
                orientation="h",  # Horizontal legend
                yanchor="bottom",  # Align the bottom of the legend
                y=1,             # Position above the plot (1.0 is the top of the plot)
                xanchor="center",  # Center the legend horizontally
                x=0.5              # Center position
        )
)

fig_eigen2.show()