# Rezepte und Cocktails (Übung)

Open in Colab: [![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/febse/opt2025-de/blob/main/Lineare-Algebra-Ex1.ipynb)



In [20]:
%pip install sympy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [ ]:
# Ingredients 100 ml vodka, 100 ml rum, 100 ml tomato juice
ingredients = np.array([100, 100, 100])

# Recipes
bloody_mary_recipe = np.array([0.3, 0, 0.7])
crazy_recipe = np.array([0.2, 0.5, 0.3])

# Nimm die Zutaten, erhöhe die erste Zutat (Vodka) um 20 Prozent, ignoriere alle anderen Zutaten
increase_vodka = np.array([1.2, 0, 0])

# Nimm die zweite Zutat (Rum), verändere die Menge nicht, ignoriere alle anderen Zutaten
keep_rum = np.array([0, 1, 0])

# Nimm die dritte Zutat (Tomato Juice), verändere die Menge nicht, ignoriere alle anderen Zutaten
keep_tomato = np.array([0, 0, 1])

In [ ]:
increase_vodka = np.stack([
    increase_vodka,
    keep_rum,
    keep_tomato
])

increase_vodka

array([[1.2, 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ]])

In [11]:
stronger_bloody_mary_recipe = bloody_mary_recipe @ increase_vodka
stronger_bloody_mary_recipe

array([0.36, 0.  , 0.7 ])

In [12]:
stronger_crazy_recipe = crazy_recipe @ increase_vodka
stronger_crazy_recipe

array([0.24, 0.5 , 0.3 ])

In [13]:
switch_vodka_and_tomato = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0]
])

In [14]:
reverse_bloody_mary_recipe = bloody_mary_recipe @ switch_vodka_and_tomato
reverse_bloody_mary_recipe

array([0.7, 0. , 0.3])

In [15]:
# Make a reverse bloody mary

reverse_bloody_mary_actual_cocktail = increase_vodka @ reverse_bloody_mary_recipe @ ingredients
reverse_bloody_mary_actual_cocktail

np.float64(114.0)

In [18]:
# How to reverse operations?

np.linalg.inv(increase_vodka)

array([[0.83333333, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ]])

## Barmanagement

Stellen wir uns vor, dass wir eine kleine Bar managen. Wir sind so spezialisiert, dass wir nur drei Getränke anbieten:

- Bloody Mary
- Rum Mary
- Crazy Cocktail

Wir können alle Cocktails in beliebigen Mengen anbieten, allerdings sind unsere Lieferungen auf 10 l Vodka, 10 l Rum und 30 l Tomatensaft
begrenzt.


In [51]:
# Unsere Cocktail Rezepte

rum_mary = np.array([0, 0.4, 0.6])

bar_recipes = np.stack([
    bloody_mary_recipe,
    rum_mary,
    crazy_recipe,
])

bar_recipes

array([[0.3, 0. , 0.7],
       [0. , 0.4, 0.6],
       [0.2, 0.5, 0.3]])

In [52]:
bar_recipes.T

array([[0.3, 0. , 0.2],
       [0. , 0.4, 0.5],
       [0.7, 0.6, 0.3]])

In [70]:
from sympy import Matrix, symbols

x1, x2, x3 = symbols('x_{bloody} x_{rum} x_{crazy}')

M = Matrix(bar_recipes.T)
M

Matrix([
[0.3, 0.0, 0.2],
[0.0, 0.4, 0.5],
[0.7, 0.6, 0.3]])

In [71]:
M @ Matrix([x1, x2, x3])

Matrix([
[              0.3*x_{bloody} + 0.2*x_{crazy}],
[                 0.5*x_{crazy} + 0.4*x_{rum}],
[0.7*x_{bloody} + 0.3*x_{crazy} + 0.6*x_{rum}]])

Wieviel von jedem Cocktail müssen wir produzieren, um die Zutaten voll auszuschöpfen?

$$
\begin{align*}
0.3 x_{\text{bloody}} + 0.0 x_{\text{rum}} + 0.2 x_{\text{crazy}} & = 10 \\
0.0 x_{\text{bloody}} + 0.4 x_{\text{rum}} + 0.3 x_{\text{crazy}} & = 10 \\
0.2 x_{\text{bloody}} + 0.5 x_{\text{rum}} + 0.3 x_{\text{crazy}} & = 30 \\
\end{align*}
$$

In [64]:
from sympy import linsolve

linsolve([M, [10, 10, 30]], [x1, x2, x3])

{(27.2727272727273, 13.6363636363636, 9.09090909090909)}

In [63]:
from numpy import linalg

linalg.solve(bar_recipes.T, [10, 10, 30])

array([27.27272727, 13.63636364,  9.09090909])