# Cocktails (Übung)

- [Recipes (shared)](https://febunisofia-my.sharepoint.com/:x:/g/personal/amarov_feb_uni-sofia_bg/EUhPq44ZYlBEoP9hs0mxvNwBtUDlucZSIMeZsdWZZFoWmQ?e=PehWdg)
- [Recipes](https://github.com/febse/data/raw/refs/heads/main/opt/Recipes.xlsx)

In [2]:
%pip install plotly sympy

import numpy as np
import plotly.graph_objects as go

Note: you may need to restart the kernel to use updated packages.


# Excel Beispiele


# Einfachere Cocktails


In [3]:
# Ingredients 100 ml vodka, 100 ml rum, 100 ml tomato juice
ingredients = np.array([100, 100, 100])

# Recipes:
bloody_mary_recipe = np.array([0.2, 0, 0.6])
rum_pure_recipe = np.array([0, 0.3, 0])
crazy_cocktail_recipe = np.array([0.1, 0.2, 0.7])

all_cocktails = np.stack([
    bloody_mary_recipe,
    rum_pure_recipe,
    crazy_cocktail_recipe
])

cocktail_names = [
    "Bloody Mary Recipe",
    "Rum Pure Recipe",
    "Crazy Cocktail Recipe"
]

cocktail_colors = [
    "red",
    "steelblue",
    "firebrick"
]

# Create a 3D scatter plot with plotly showing the rows of all_cocktails as vectors 

fig = go.Figure()

# Add each cocktail as a vector
for i, cocktail in enumerate(all_cocktails):
    fig.add_trace(go.Scatter3d(
        x=[0, cocktail[0]],  # Start at origin (0, 0, 0)
        y=[0, cocktail[1]],
        z=[0, cocktail[2]],
        mode='lines+markers',
        name=cocktail_names[i],
        line=dict(color=cocktail_colors[i], width=5),
        marker=dict(size=5)
    ))

# Set plot layout
fig.update_layout(
    title="3D Diagram der Cocktails",
    scene=dict(
        xaxis_title="Vodka",
        yaxis_title="Rum",
        zaxis_title="Tomatensaft"
    )
)

# Show the plot
fig.show()

## Modifikation von Rezepten


In [4]:

# Nimm die Zutaten, erhöhe die erste Zutat (Vodka) um 20 Prozent, ignoriere alle anderen Zutaten
increase_vodka = np.array([1.2, 0, 0])

# Nimm die zweite Zutat (Rum), verändere die Menge nicht, ignoriere alle anderen Zutaten
keep_rum = np.array([0, 1, 0])

# Nimm die dritte Zutat (Tomato Juice), verändere die Menge nicht, ignoriere alle anderen Zutaten
keep_tomato = np.array([0, 0, 1])

In [5]:
increase_vodka = np.stack([
    increase_vodka,
    keep_rum,
    keep_tomato
])

increase_vodka

array([[1.2, 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ]])

In [6]:
stronger_bloody_mary_recipe = bloody_mary_recipe @ increase_vodka
stronger_bloody_mary_recipe

array([0.24, 0.  , 0.6 ])

In [7]:
stronger_crazy_recipe = crazy_cocktail_recipe @ increase_vodka
stronger_crazy_recipe

array([0.12, 0.2 , 0.7 ])

In [8]:
switch_vodka_and_tomato = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0]
])
switch_vodka_and_tomato

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [9]:
reverse_bloody_mary_recipe = bloody_mary_recipe @ switch_vodka_and_tomato
reverse_bloody_mary_recipe

array([0.6, 0. , 0.2])

In [10]:
# Make a reverse bloody mary

reverse_bloody_mary_actual_cocktail = increase_vodka @ reverse_bloody_mary_recipe @ ingredients
reverse_bloody_mary_actual_cocktail

np.float64(92.0)

In [11]:
# How to reverse operations?

np.linalg.inv(increase_vodka)

array([[0.83333333, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ]])

## Barmanagement

Stellen wir uns vor, dass wir eine kleine Bar managen. Wir sind so spezialisiert, dass wir nur drei Getränke anbieten:

- Bloody Mary
- Rum Mary
- Crazy Cocktail

Wir können alle Cocktails in beliebigen Mengen anbieten, allerdings sind unsere Lieferungen auf 10 l Vodka, 10 l Rum und 30 l Tomatensaft
begrenzt.


In [12]:
# Unsere Cocktail Rezepte

rum_mary = np.array([0, 0.4, 0.6])

bar_recipes = np.stack([
    bloody_mary_recipe,
    rum_mary,
    crazy_cocktail_recipe,
])

bar_recipes

array([[0.2, 0. , 0.6],
       [0. , 0.4, 0.6],
       [0.1, 0.2, 0.7]])

In [13]:
bar_recipes.T

array([[0.2, 0. , 0.1],
       [0. , 0.4, 0.2],
       [0.6, 0.6, 0.7]])

In [14]:
from sympy import Matrix, symbols

x1, x2, x3 = symbols('x_{bloody} x_{rum} x_{crazy}')
y1, y2, y3 = symbols('y_{vodka} y_{rum} y_{tomato}')

x = Matrix([x1, x2, x3])
y = Matrix([y1, y2, y3])

M = Matrix(bar_recipes)
M

Matrix([
[0.2, 0.0, 0.6],
[0.0, 0.4, 0.6],
[0.1, 0.2, 0.7]])

In [15]:
M.T

Matrix([
[0.2, 0.0, 0.1],
[0.0, 0.4, 0.2],
[0.6, 0.6, 0.7]])

In [16]:
x

Matrix([
[x_{bloody}],
[   x_{rum}],
[ x_{crazy}]])

In [17]:
M.T @ y

Matrix([
[              0.1*y_{tomato} + 0.2*y_{vodka}],
[                0.4*y_{rum} + 0.2*y_{tomato}],
[0.6*y_{rum} + 0.7*y_{tomato} + 0.6*y_{vodka}]])

In [18]:
M.T @ x

Matrix([
[              0.2*x_{bloody} + 0.1*x_{crazy}],
[                 0.2*x_{crazy} + 0.4*x_{rum}],
[0.6*x_{bloody} + 0.7*x_{crazy} + 0.6*x_{rum}]])

Wieviel von jedem Cocktail müssen wir produzieren, um die Zutaten voll auszuschöpfen?

$$
\begin{align*}
0.3 x_{\text{bloody}} + 0.0 x_{\text{rum}} + 0.2 x_{\text{crazy}} & = 10 \quad \text{Vodka} \\
0.0 x_{\text{bloody}} + 0.4 x_{\text{rum}} + 0.3 x_{\text{crazy}} & = 10 \quad \text{Rum} \\
0.2 x_{\text{bloody}} + 0.5 x_{\text{rum}} + 0.3 x_{\text{crazy}} & = 30 \quad \text{Tomatensaft} \\
\end{align*}
$$

In [19]:
from sympy import linsolve

linsolve([M, [10, 10, 30]], [x1, x2, x3])

{(-550.000000000001, -275.0, 200.0)}

In [20]:
from numpy import linalg

linalg.solve(bar_recipes.T, [10, 10, 30])

array([ 125.,  100., -150.])

In [61]:
# Scale in the x direction

def create_frame_data(v1, v2, A):
    v1_tr, v2_tr = A @ v1, A @ v2

    tr_sum = v1_tr + v2_tr

    return [
        go.Scatter(
            x=[0, v1_tr[0]],
            y=[0, v1_tr[1]],
            mode='lines+markers',
            name='V1',
            line=dict(color='blue', width=1),
            marker=dict(size=2)
        ),
        go.Scatter(
            x=[0, v2_tr[0]],
            y=[0, v2_tr[1]],
            mode='lines+markers',
            name='V2',
            line=dict(color='red', width=1),
            marker=dict(size=2)
        ),
        go.Scatter(
            x=[0, tr_sum[0]],
            y=[0, tr_sum[1]],
            mode='lines+markers',
            name='V1 + V2',
            line=dict(color='green', width=1),
            marker=dict(size=2)
        ),
        go.Scatter(
            x=[0, v1_tr[0], tr_sum[0], v2_tr[0], 0],  # Define the polygon vertices
            y=[0, v1_tr[1], tr_sum[1], v2_tr[1], 0],
            fill='toself',
            fillcolor='rgba(0, 100, 200, 0.2)',  # Set fill color with transparency
            line=dict(color='rgba(255,255,255,0)'),  # No border line
            name='Area'
        )
    ]

def create_animation(v1, v2, A_list):    
    # Plot the unit vectors and their sum
    A = A_list[0]

    fig = go.Figure(
        data=create_frame_data(v1, v2, A),
        layout=go.Layout(
            title='Area and stretching in the x direction',
            xaxis=dict(title='x', range=[-2.3, 2.3]),  # Set X-axis range
            yaxis=dict(title='y', range=[-2.3, 2.3]),  # Set Y-axis range
            showlegend=True,
            width=800,
            height=600
        ),
    )

    frames = [go.Frame(data = create_frame_data(v1, v2, A_frame)) for A_frame in A_list]

    fig.update_layout(width=600, height=450,
            updatemenus = [
                dict(type = "buttons",
                    buttons = [
                        dict(
                    args = [None, {"frame": {"duration": 50, "redraw": False},
                                    "fromcurrent": True, "transition": {"duration": 10}}],
                    label = "Play",
                    method = "animate",
                    )])])

    fig.update(frames=frames)

    return fig

unit1 = np.array([1, 0])
unit2 = np.array([0, 1])

A_list = [np.identity(2)] + [
    np.array([[x, 0], [0, 1]]) for x in np.linspace(1, 2, 50)
]

fig1 = create_animation(unit1, unit2, A_list)
fig1.show()


In [62]:
# Scale in the y direction

fig2 = create_animation(unit1, unit2, [
    np.array([[1, 0], [0, y]]) for y in np.linspace(1, 2, 50)
])
fig2.show()

In [63]:
# Scale in the x and y direction

fig3 = create_animation(unit1, unit2, [
    np.array([[x, 0], [0, y]]) for x, y in zip(np.linspace(1, 2, 50), np.linspace(1, 2, 50))
])
fig3.show()

In [64]:
# Sheer in the x direction

fig4 = create_animation(unit1, unit2, [
    np.array([[1, x], [0, 1]]) for x in np.linspace(0, 1, 50)
])
fig4.show()

In [65]:
# Sheer in the y direction

fig5 = create_animation(unit1, unit2, [
    np.array([[1, 0], [x, 1]]) for x in np.linspace(0, 1, 50)
])
fig5.show()


In [76]:
# Sheer in the x and y direction

fig6 = create_animation(unit1, unit2, [
    np.array([[1, x], [y, 1]]) for x, y in zip(np.linspace(0, 1, 50), np.linspace(0, 1, 50))
])
fig6.show()


In [ ]:
# Scale and shear in the in both directions

fig7 = create_animation(unit1, unit2, [
    np.array([[x, x1], [y1, y]]) for x, y, x1, y1 in zip(np.linspace(1, 2, 50), np.linspace(1, 2, 50), np.linspace(0, 1, 50), np.linspace(0, 1, 50))])
fig7.show()

In [ ]:
np.ones((2, 2)) @ np.array([-2, 5])

array([3., 3.])

In [ ]:
np.ones((2, 2)) @ np.array([-1, 1])

array([0., 0.])

In [86]:
np.linalg.det(np.ones((2, 2)))

np.float64(0.0)