# Cocktails (Übung)

Open in Colab: [![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/febse/opt2025-de/blob/main/Lineare-Algebra-Ex1.ipynb)



In [7]:
import numpy as np

# Ingredients 100 ml vodka, 100 ml rum, 100 ml tomato juice
ingredients = np.array([100, 100, 100])

# Recipes
bloody_mary_recipe = np.array([0.3, 0, 0.7])
crazy_recipe = np.array([0.2, 0.5, 0.3])

# Recipes in ml
add_vodka = np.array([1.2, 0, 0])
keep_rum = np.array([0, 1, 0])
keep_tomato = np.array([0, 0, 1])

In [15]:

increase_vodka = np.stack([
    add_vodka,
    keep_rum,
    keep_tomato
])

increase_vodka

array([[1.2, 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ]])

In [9]:
stronger_bloody_mary_recipe = bloody_mary_recipe @ increase_vodka
stronger_bloody_mary_recipe

array([0.36, 0.  , 0.7 ])

In [16]:
stronger_crazy_recipe = crazy_recipe @ increase_vodka
stronger_crazy_recipe

array([0.24, 0.5 , 0.3 ])

In [ ]:
switch_vodka_and_tomato = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0]
])

In [12]:
reverse_bloody_mary_recipe = bloody_mary_recipe @ switch_vodka_and_tomato
reverse_bloody_mary_recipe

array([0.7, 0. , 0.3])

In [14]:
# Make a reverse bloody mary

reverse_bloody_mary_actual_cocktail = increase_vodka @ reverse_bloody_mary_recipe @ ingredients
reverse_bloody_mary_actual_cocktail

np.float64(114.0)

In [ ]:
# 