# Cocktails (Übung)

- [Recipes (shared)](https://febunisofia-my.sharepoint.com/:x:/g/personal/amarov_feb_uni-sofia_bg/EUhPq44ZYlBEoP9hs0mxvNwBtUDlucZSIMeZsdWZZFoWmQ?e=PehWdg)
- [Recipes](https://github.com/febse/data/raw/refs/heads/main/opt/Recipes.xlsx)

In [27]:
%pip install plotly sympy

import numpy as np
import plotly.graph_objects as go


Note: you may need to restart the kernel to use updated packages.


# Excel Beispiele


# Einfachere Cocktails


In [28]:
# Ingredients 100 ml vodka, 100 ml rum, 100 ml tomato juice
ingredients = np.array([100, 100, 100])

# Recipes:
bloody_mary_recipe = np.array([0.2, 0, 0.6])
rum_pure_recipe = np.array([0, 0.3, 0])
crazy_cocktail_recipe = np.array([0.1, 0.2, 0.7])

all_cocktails = np.stack([
    bloody_mary_recipe,
    rum_pure_recipe,
    crazy_cocktail_recipe
])

cocktail_names = [
    "Bloody Mary Recipe",
    "Rum Pure Recipe",
    "Crazy Cocktail Recipe"
]

cocktail_colors = [
    "red",
    "steelblue",
    "firebrick"
]

# Create a 3D scatter plot with plotly showing the rows of all_cocktails as vectors 

fig = go.Figure()

# Add each cocktail as a vector
for i, cocktail in enumerate(all_cocktails):
    fig.add_trace(go.Scatter3d(
        x=[0, cocktail[0]],  # Start at origin (0, 0, 0)
        y=[0, cocktail[1]],
        z=[0, cocktail[2]],
        mode='lines+markers',
        name=cocktail_names[i],
        line=dict(color=cocktail_colors[i], width=5),
        marker=dict(size=5)
    ))

# Set plot layout
fig.update_layout(
    title="3D Scatter Plot of Cocktail Vectors",
    scene=dict(
        xaxis_title="Vodka",
        yaxis_title="Rum",
        zaxis_title="Tomatensaft"
    )
)

# Show the plot
fig.show()

## Modifikation von Rezepten


In [29]:

# Nimm die Zutaten, erhöhe die erste Zutat (Vodka) um 20 Prozent, ignoriere alle anderen Zutaten
increase_vodka = np.array([1.2, 0, 0])

# Nimm die zweite Zutat (Rum), verändere die Menge nicht, ignoriere alle anderen Zutaten
keep_rum = np.array([0, 1, 0])

# Nimm die dritte Zutat (Tomato Juice), verändere die Menge nicht, ignoriere alle anderen Zutaten
keep_tomato = np.array([0, 0, 1])

In [30]:
increase_vodka = np.stack([
    increase_vodka,
    keep_rum,
    keep_tomato
])

increase_vodka

array([[1.2, 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ]])

In [31]:
stronger_bloody_mary_recipe = bloody_mary_recipe @ increase_vodka
stronger_bloody_mary_recipe

array([0.24, 0.  , 0.6 ])

In [32]:
stronger_crazy_recipe = crazy_cocktail_recipe @ increase_vodka
stronger_crazy_recipe

array([0.12, 0.2 , 0.7 ])

In [33]:
switch_vodka_and_tomato = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0]
])
switch_vodka_and_tomato

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [34]:
reverse_bloody_mary_recipe = bloody_mary_recipe @ switch_vodka_and_tomato
reverse_bloody_mary_recipe

array([0.6, 0. , 0.2])

In [35]:
# Make a reverse bloody mary

reverse_bloody_mary_actual_cocktail = increase_vodka @ reverse_bloody_mary_recipe @ ingredients
reverse_bloody_mary_actual_cocktail

np.float64(92.0)

In [36]:
# How to reverse operations?

np.linalg.inv(increase_vodka)

array([[0.83333333, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ]])

## Barmanagement

Stellen wir uns vor, dass wir eine kleine Bar managen. Wir sind so spezialisiert, dass wir nur drei Getränke anbieten:

- Bloody Mary
- Rum Mary
- Crazy Cocktail

Wir können alle Cocktails in beliebigen Mengen anbieten, allerdings sind unsere Lieferungen auf 10 l Vodka, 10 l Rum und 30 l Tomatensaft
begrenzt.


In [38]:
# Unsere Cocktail Rezepte

rum_mary = np.array([0, 0.4, 0.6])

bar_recipes = np.stack([
    bloody_mary_recipe,
    rum_mary,
    crazy_cocktail_recipe,
])

bar_recipes

array([[0.2, 0. , 0.6],
       [0. , 0.4, 0.6],
       [0.1, 0.2, 0.7]])

In [39]:
bar_recipes.T

array([[0.2, 0. , 0.1],
       [0. , 0.4, 0.2],
       [0.6, 0.6, 0.7]])

In [43]:
from sympy import Matrix, symbols

x1, x2, x3 = symbols('x_{bloody} x_{rum} x_{crazy}')

M = Matrix(bar_recipes.T)
M

Matrix([
[0.2, 0.0, 0.1],
[0.0, 0.4, 0.2],
[0.6, 0.6, 0.7]])

In [41]:
M @ Matrix([x1, x2, x3])

Matrix([
[              0.2*x_{bloody} + 0.1*x_{crazy}],
[                 0.2*x_{crazy} + 0.4*x_{rum}],
[0.6*x_{bloody} + 0.7*x_{crazy} + 0.6*x_{rum}]])

Wieviel von jedem Cocktail müssen wir produzieren, um die Zutaten voll auszuschöpfen?

$$
\begin{align*}
0.3 x_{\text{bloody}} + 0.0 x_{\text{rum}} + 0.2 x_{\text{crazy}} & = 10 \quad \text{Vodka} \\
0.0 x_{\text{bloody}} + 0.4 x_{\text{rum}} + 0.3 x_{\text{crazy}} & = 10 \quad \text{Rum} \\
0.2 x_{\text{bloody}} + 0.5 x_{\text{rum}} + 0.3 x_{\text{crazy}} & = 30 \quad \text{Tomatensaft} \\
\end{align*}
$$

In [ ]:
from sympy import linsolve

linsolve([M, [10, 10, 30]], [x1, x2, x3])

{(250.0, 200.0, -300.0)}

In [52]:
from numpy import linalg

linalg.solve(bar_recipes.T, [10, 10, 30])

array([ 125.,  100., -150.])